<?php
	define("PLEX_PRODUCT_INFO",  "8130");
	define("PLEX_CALCULATE_SALES_TAX",  "9312");
	define("PLEX_WRITE_NEW_CUSTOMER",  "10428");
	define("PLEX_UPDATE_CUSTOMER",  "11312");
	define("PLEX_WRITE_NEW_BILL_TO_SHIP_TO_ADDRESS",  "10429");
	define("PLEX_WRITE_NEW_BILL_TO",  "10429");
	define("PLEX_GET_SHIP_TO_BILL_TO_ADDRESS",  "810");
	define("PLEX_WRITE_NEW_ORDER",  "10410");
	define("PLEX_WRITE_NEW_ORDER_LINE",  "10408");
	define("PLEX_GET_PRODUCT_INVENTORY",  "15762");
	define("PLEX_GET_ORDER_STATUS",  "10409");
	
?>